### ISSUE TITLE
FEATURE: Orthographic projection

### ISSUE THREAD

**Issue by ajjackson** [ajjackson/ascii-phonons#12]
In many cases an orthographic projection is more useful than one with perspective.
- Modify the camera creator to allow an orthographic view to be requested.
- Add option to GUI, perhaps as a pre-ticked "perspective" checkbox

**Comment by lucydot** [comment]
Hi Adam - I'd like to use this feature with the CLI. It's in the documentation as being an option but it isn't listed under `./scripts/ascii-phonons -h`. Can't find any reference to it in the corresponding code either. Bug?

**Comment by ajjackson** [comment]
You are right, this was a silly oversight! I have now added the flag to the CLI where it should have been and pushed this up.

You can also use the orthographic option from the CLI without the latest version by using a config file by setting "orthographic = yes" in a config file included with `--config MYFILE.conf`.

When testing this I noticed some odd glitches in the graphics when actually using the orthographic projection, with atoms appearing superimposed. It's not clear what would cause this; the rendering pipeline was changed since I previously tested orthographic mode, but that should only affect the way the outlines and bounding box are drawn. It may need further investigation!

**Comment by ajjackson** [comment]
Ok, I played with the clip distance and commit 86a5e050534f35e46ce9a687ef6d6e2d6bd30704 fixes the glitches for me! If it works out for you too then I will close this issue again.

**Comment by lucydot** [comment]
New commit works for me - thanks Adam.
