### ISSUE TITLE
Correct way to cite ascii-phonons

### ISSUE THREAD

**Issue by Fellow-baka** [ajjackson/ascii-phonons#30]
Thanks for the nice code.
There are two papers mentioned in the http://ascii-phonons.readthedocs.io : http://dx.doi.org/10.1063/1.4917044 and http://dx.doi.org/10.1103/PhysRevB.92.144308 .
Should I cite one of those or directly add github repository link?

**Comment by ajjackson** [comment]
Hi, thanks for asking! Neither of those papers describe the _ascii-phonons_ code itself so I don't think it would be right to ask for you to cite them when reporting your own use of _ascii-phonons_. You might wish to refer to one if making a comment about its usage in the analysis of results, but this is totally at your discretion.

I can mint a DOI for the latest release using Zenodo, which allows you to refer to the specific version you used. That's the best thing for reproducibility, really.

I shall also provide a citation file which summarises the bibliographic information for the code itself; a standard format has now been developed for these: https://citation-file-format.github.io How to use this citation in a formal paper is up to the publisher. Something like
> Jackson, A. J. (2016) ascii-phonons v1.0.0, doi:not/yet/existing, avail. https://github.com/ajjackson/ascii-phonons [June 2018]

would be suitable.

Ideally I would submit it to https://joss.theoj.org/ but some more work is needed to bring it up to their standards.

**Comment by ajjackson** [comment]
I have set up a DOI for the latest release and a citation file. It would be great to revisit the codebase, clean it up a bit and submit to a journal but I don't have a timescale for that work at present.
